"""Functions that deal with cross-references (xrefs).

There are 2 groups of xrefs: CODE and DATA references. All xrefs are kept in the bTree except the ordinary execution flow to the next instruction. The ordinary execution flow to the next instruction is kept in flags (see bytes.hpp)

The source address of an xref must be an item head (is_head) or a structure member id. Even if an xref is generated by an element in the middle of the item, the item head address must be used. There are some exceptions to the rule but they are not worth mentioning here.

Xrefs are automatically sorted by addresses. However, the flow to the next instruction is always at the beginning of the list.

Xrefs are usually created by the processor module, as a reaction to the ev_emu_insn event. Plugins may create xrefs too but please note that upon a reanalysis of an item, all its xrefs, except the ones marked with XREF_USER, are deleted by the kernel.

.. tip::
   The `IDA Domain API <https://ida-domain.docs.hex-rays.com/>`_ simplifies
   common tasks and provides better type hints, while remaining fully compatible
   with IDAPython for advanced use cases.

   For cross-reference operations, see :mod:`ida_domain.xrefs`."""

def create_switch_xrefs(ea, si):
    """
    This function creates xrefs from the indirect jump.

    Usually there is no need to call this function directly because the kernel
    will call it for switch tables

    Note: Custom switch information are not supported yet.

    :param ea: address of the 'indirect jump' instruction
    :param si: switch information

    :returns: Boolean
    """
    pass


def calc_switch_cases(ea, si):
    """
    Get information about a switch's cases.

    The returned information can be used as follows:

        for idx in range(len(results.cases)):
            cur_case = results.cases[idx]
            for cidx in range(len(cur_case)):
                print("case: %d" % cur_case[cidx])
            print("  goto 0x%x" % results.targets[idx])

    :param ea: address of the 'indirect jump' instruction
    :param si: switch information

    :returns: a structure with 2 members: 'cases', and 'targets'.
    """
    pass

def create_switch_table(ea, si):
    """
    Create switch table from the switch information

    :param ea: address of the 'indirect jump' instruction
    :param si: switch information

    :returns: Boolean
    """
    pass
